# Core Properties
spring.application.name=demo
logging.file.path=logs
logging.level.root=WARN
logging.level.com.learn.springboot=WARN

# Server Properties
server.port=8080

# Data Properties
spring.datasource.url=jdbc:mysql://localhost:3306/companydb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# Data Migration Properties using Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml